# Generated by Django 6.0.8 on 2026-10-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_savedteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='is_preset',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
