# Generated by Django 6.0.8 on 2026-10-03 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_game_aliases_game_is_preset'),
        ('tournaments', '0008_remove_claim_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='groups.game'),
        ),
    ]
