# Generated by Django 6.0.8 on 2026-09-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_statsboard_options_statsboard_favourited_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statsboard',
            options={'ordering': [models.OrderBy(models.F('favourited_at'), nulls_last=True), '-created_at']},
        ),
    ]
