# Generated by Django 6.0.8 on 2026-09-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_statsboard_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsboard',
            name='group',
        ),
    ]
