# Generated by Django 6.0.8 on 2026-09-11 17:35

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_url_user_google_sub'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'That username is taken.'}, help_text='Your @handle. Letters, numbers and underscores only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Usernames can only contain letters, numbers and underscores.', regex='^[A-Za-z0-9_]+$')]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='uniq_username_ci'),
        ),
    ]
