# Generated by Django 6.0.8 on 2026-09-04 20:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('joined_round', models.IntegerField(default=0, help_text='0 for an original entrant; >0 marks a late entry.')),
                ('eliminated', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(blank=True, related_name='entrants', to='groups.player')),
                ('replaced_by', models.ForeignKey(blank=True, help_text='Substitution (plan §4, NEW 11): the slot persists, the person in it changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='tournaments.entrant')),
            ],
            options={
                'ordering': ['seed', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TeamGenerationConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('together', 'Must be on the same team'), ('apart', 'Must be on different teams'), ('locked', 'Locked to a specific team')], max_length=10)),
                ('team_index', models.IntegerField(blank=True, help_text='Target team for a LOCKED constraint.', null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_constraints', to='groups.group')),
                ('players', models.ManyToManyField(related_name='team_constraints', to='groups.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('single', 'Single elimination'), ('double', 'Double elimination'), ('rr', 'Round robin'), ('swiss', 'Swiss'), ('ffa', 'Free-for-all')], max_length=8)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('complete', 'Complete')], db_index=True, default='draft', max_length=8)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('third_place_match', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('public_slug', models.SlugField(blank=True, max_length=16, unique=True)),
                ('claim_token', models.CharField(blank=True, db_index=True, max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Null for a no-account quick-start bracket that has not been claimed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='groups.group')),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='groups.gamemode')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='groups.season')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('host', 'Host'), ('cohost', 'Co-host')], default='cohost', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_roles', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bracket', models.CharField(choices=[('main', 'Main'), ('losers', 'Losers'), ('final', 'Grand final'), ('third', 'Third place')], default='main', max_length=8)),
                ('best_of', models.IntegerField(choices=[(1, 'Bo1'), (3, 'Bo3'), (5, 'Bo5'), (7, 'Bo7')], default=1)),
                ('score', models.JSONField(blank=True, default=dict)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournaments.entrant')),
                ('b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournaments.entrant')),
                ('next_match_lose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.match')),
                ('next_match_win', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.match')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_matches', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.entrant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['bracket', 'round_no', 'position'],
            },
        ),
        migrations.AddField(
            model_name='entrant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrants', to='tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='FFAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('points', models.FloatField(default=0)),
                ('entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffa_results', to='tournaments.entrant')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffa_results', to='tournaments.match')),
            ],
            options={
                'ordering': ['match', 'placement'],
                'constraints': [models.UniqueConstraint(fields=('match', 'entrant'), name='uniq_ffa_result_per_entrant')],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('disputed', 'Disputed')], db_index=True, default='active', max_length=10)),
                ('entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='tournaments.entrant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entrant', 'user'), name='uniq_entrant_participation')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elo', models.FloatField(default=1200)),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='groups.gamemode')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='groups.player')),
            ],
            options={
                'ordering': ['-elo'],
                'indexes': [models.Index(fields=['mode', '-elo'], name='tournaments_mode_id_c2919f_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'mode'), name='uniq_rating_per_mode')],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['group', 'state', '-created_at'], name='tournaments_group_i_94e9d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='uniq_tournament_role'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'round_no'], name='tournaments_tournam_0de720_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'bracket', 'round_no', 'position'), name='uniq_match_slot'),
        ),
        migrations.AddIndex(
            model_name='entrant',
            index=models.Index(fields=['tournament', 'seed'], name='tournaments_tournam_b749e1_idx'),
        ),
    ]
