# Generated by Django 6.0.8 on 2026-09-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': [models.OrderBy(models.F('favourited_at'), nulls_last=True), '-created_at']},
        ),
        migrations.AddField(
            model_name='tournament',
            name='favourited_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this was pinned to the top of the list. Null if it is not.', null=True),
        ),
    ]
