# Generated by Django 6.0.8 on 2026-09-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_options_tournament_favourited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the tournament list without losing its results.'),
        ),
    ]
