# Generated by Django 6.0.8 on 2026-09-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgenerationconstraint',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teamgenerationconstraint',
            name='players',
        ),
        migrations.RemoveIndex(
            model_name='tournament',
            name='tournaments_group_i_94e9d5_idx',
        ),
        migrations.DeleteModel(
            name='TeamGenerationConstraint',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='season',
        ),
    ]
