# Generated by Django 6.0.8 on 2026-09-15 03:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_backfill_self_roster_entries'),
        ('tournaments', '0004_remove_teamgenerationconstraint_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('drafting', 'Drafting teams'), ('active', 'Active'), ('complete', 'Complete')], db_index=True, default='draft', max_length=8),
        ),
        migrations.CreateModel(
            name='TeamDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('captain_mode', models.CharField(choices=[('random', 'Randomised captains'), ('manual', 'Chosen captains')], default='random', max_length=8)),
                ('pick_order', models.JSONField(blank=True, default=list, help_text='Team indexes in the order they pick, one full cycle per round.')),
                ('picks_made', models.PositiveSmallIntegerField(default=0, help_text='How far through `pick_order` the draft has got.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_draft', to='tournaments.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(help_text='0-based index into the pick order.')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('captain_label', models.CharField(help_text="The captain's name as typed, so an anonymous draft still reads correctly.", max_length=80)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_draft_teams', to='groups.player')),
                ('captain_user', models.ForeignKey(blank=True, help_text='Set when the captain is a linked account. Unused until live drafting lands.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_drafts', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.teamdraft')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='The picked name as typed.', max_length=80)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_picks', to='groups.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='tournaments.draftteam')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='tournaments.teamdraft')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.AddConstraint(
            model_name='draftteam',
            constraint=models.UniqueConstraint(fields=('draft', 'position'), name='uniq_draft_team_position'),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('draft', 'ordinal'), name='uniq_draft_pick_ordinal'),
        ),
    ]
