# Generated by Django 6.0.8 on 2026-09-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_state_teamdraft_draftteam_draftpick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdraft',
            name='pool_user_ids',
            field=models.JSONField(blank=True, default=list, help_text='User ids of linked accounts in the draft pool. Visibility only.'),
        ),
    ]
