# Generated by Django 6.0.8 on 2026-09-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_remove_ffaresult_uniq_ffa_result_per_entrant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='claim_token',
        ),
    ]
