# Generated by Django 6.0.8 on 2026-09-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('stats', '0006_remove_statsboard_group'),
        ('tournaments', '0004_remove_teamgenerationconstraint_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='group',
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='uniq_group_member',
        ),
        migrations.RemoveConstraint(
            model_name='season',
            name='uniq_season_per_group',
        ),
        migrations.RemoveConstraint(
            model_name='game',
            name='uniq_game_per_group',
        ),
        migrations.RemoveField(
            model_name='season',
            name='group',
        ),
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
