# Generated by Django 6.0.8 on 2026-09-08 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('emoji', models.CharField(default='🔱', help_text='Stamped once per point. Long enough for multi-codepoint emoji.', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatsBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(blank=True, help_text='Optional — a board can exist without a crew behind it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_boards', to='groups.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stats_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded', models.BooleanField(db_index=True, default=False)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats_link', to='tournaments.tournament')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='stats.statscolumn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order within the board.')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='stats.statsboard')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text="Shown on the board. Falls back to the linked player's name.", max_length=60)),
                ('position', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_rows', to='groups.player')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='stats.statstable')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='statscolumn',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='stats.statstable'),
        ),
        migrations.CreateModel(
            name='BoardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('editor', 'Editor')], default='editor', max_length=10)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_access', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='stats.statsboard')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('board', 'user'), name='uniq_board_access')],
            },
        ),
        migrations.CreateModel(
            name='StatsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stats.statscolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stats.statsrow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('row', 'column'), name='uniq_entry_per_row_column'), models.CheckConstraint(condition=models.Q(('count__gte', 0)), name='entry_count_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='statscolumn',
            constraint=models.UniqueConstraint(fields=('table', 'name'), name='uniq_column_per_table'),
        ),
    ]
