# Generated by Django 6.0.8 on 2026-09-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardlink',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Feeds every automatic column on this table.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='stats.statstable'),
        ),
        migrations.AddField(
            model_name='statscolumn',
            name='display',
            field=models.CharField(choices=[('emoji', 'A mark per point'), ('number', 'A number')], default='emoji', max_length=10),
        ),
        migrations.AddField(
            model_name='statscolumn',
            name='role',
            field=models.CharField(choices=[('manual', 'Counted by hand'), ('played', 'Games played'), ('won', 'Games won'), ('lost', 'Games lost'), ('tournaments_won', 'Tournaments won')], db_index=True, default='manual', help_text='What a linked tournament counts into this column.', max_length=20),
        ),
        migrations.AlterField(
            model_name='boardlink',
            name='column',
            field=models.ForeignKey(blank=True, help_text='A single hand-made tally to mark instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='stats.statscolumn'),
        ),
        migrations.AddConstraint(
            model_name='boardlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('column__isnull', True), ('table__isnull', False)), models.Q(('column__isnull', False), ('table__isnull', True)), _connector='OR'), name='link_targets_a_table_or_a_column'),
        ),
        migrations.AddConstraint(
            model_name='statscolumn',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'manual'), _negated=True), fields=('table', 'role'), name='uniq_automatic_role_per_table'),
        ),
    ]
