# Generated by Django 6.0.8 on 2026-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_boardlink_table_statscolumn_display_statscolumn_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardlink',
            name='awarded_player_ids',
            field=models.JSONField(blank=True, default=list, help_text='Players this link credited, so the credit can be undone.'),
        ),
    ]
